<img src = 'https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true' width="240" height="360">
# __Assignment: Numpy and Pandas__
### Level: 1

### 1. Create a null vector of size 7 but the third and last value as 2.

In [84]:
import numpy as np
def generate():
    # Write your code here
    arr1=np.zeros((7))
    arr2=[(0,0,2,0,0,0,2)]
    s_arr=np.concatenate(arr1+arr2)   
    return s_arr # your variable 
generate()

2


array([0., 0., 2., 0., 0., 0., 2.])

### 2. Create a vector of size 9 with values ranging from 0 to 2, both excluded.

In [53]:
import numpy as np
def generate():
    # Write your code here
    arr2=np.arange(0.1,2,0.23)
    return arr2 # your variable
generate()

array([0.1 , 0.33, 0.56, 0.79, 1.02, 1.25, 1.48, 1.71, 1.94])

### 3. Convert the first character of each element in a series to uppercase? And return the new series.

In [47]:
import pandas as pd
series = pd.Series(['how', 'to', 'learn', 'data science?'])
def generate():
    # your code
    s=series.str.capitalize()
    
    return s # your variable for new series
generate() 

0              How
1               To
2            Learn
3    Data science?
dtype: object

### 4. Given a 3*3 matrix named matrix_fab, From each element of this matrix subtract the mean of that row, name this matrix as matrix_sub. Divide each element of this matrix by twice of the largest element to get matrix_norm. Print it out.

In [108]:
import numpy as np
arr = np.arange(0,9)                                
matrix_fab = arr.reshape(3,3)
def generate():
    # Write your code here
    matrix_sub=matrix_fab.mean(axis=1)
    matrix_sub=matrix_fab - matrix_sub
    max_num = np.max(matrix_sub)
    matrix_norm = matrix_sub/(max_num*2)
    print(matrix_norm)
    
    # print matrix_norm
    return None
generate()

[[-0.1 -0.3 -0.5]
 [ 0.2  0.  -0.2]
 [ 0.5  0.3  0.1]]


### 5. Create a random vector of size 12 , sort it in decreasing order, make 4*3 array using it.
Hint: use reshape and sort function.

In [76]:
import numpy as np
def generate():
    # Write your code here
    des_arr3=np.random.rand(12)
    des_arr= np.sort(des_arr3)[::-1]
    return des_arr.reshape(4,3) # your variable
generate()

array([[0.97087439, 0.92682733, 0.91334476],
       [0.8640088 , 0.71879441, 0.50163779],
       [0.4222843 , 0.41698627, 0.16994878],
       [0.10381642, 0.08093414, 0.03181405]])

### 6. Below is Python dictionary data and Python list labels. Create a DataFrame df from this dictionary data which has index as labels. Select the rows where the age is missing, i.e. is NaN.

In [75]:
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
import pandas as pd
def generate():
    df= pd.DataFrame(data,index=labels)
    print(df[df['age'].isnull()])
    return df  # your variable
generate()

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes


animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 7. From the give dataframe df, in the 'animal' column change the 'dog' entries to 'Labrador', change the age in row 'd' to 2.7 and calculate the mean age (name it mean_age) for each different animal in df. Print df and return mean_age.

In [79]:
import pandas as pd
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
def generate():
    # write your code here
    df=pd.DataFrame(data,index=labels)
    df['animal'] = df['animal'].replace('dog','Labrador')
    df.loc['d','age']= 2.7
    print(df)
    mean_age=df.groupby('animal')['age'].mean()
    
    # Also print df
    return mean_age # your variable i.e mean_age
generate()

     animal  age  visits priority
a       cat  2.5       1      yes
b       cat  3.0       3      yes
c     snake  0.5       2       no
d  Labrador  2.7       3      yes
e  Labrador  5.0       2       no
f       cat  2.0       3       no
g     snake  4.5       1       no
h       cat  NaN       1      yes
i  Labrador  7.0       2       no
j  Labrador  3.0       1       no


animal
Labrador    4.425
cat         2.500
snake       2.500
Name: age, dtype: float64

### 8.  From the given dataframe get the positions where values of two columns match?

In [83]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})
def generate():
    # your code here
    s=np.where(df.fruit1==df.fruit2)
    print(s)
        
    return None
generate()

(array([5, 8, 9], dtype=int64),)


### 9. Find the positions of numbers that are multiples of 4 from a series? Print series and return position. Hint: use argwhere.

In [134]:
import pandas as pd
import numpy as np
series = pd.Series(np.random.randint(1, 10, 7))
def generate():
    # your code here
    mul= np.argwhere((series%4)==0)
    print(series)
    return mul # your variable
generate()

0    1
1    8
2    3
3    4
4    3
5    4
6    9
dtype: int32


array([[1],
       [3],
       [5]], dtype=int64)

### 10. Stack two given series vertically and horizontally ? Print out both.

In [183]:
import pandas as pd
import numpy as np
series1 = pd.Series(range(5))
series2 = pd.Series(list('abcde'))
def generate():
    # your code 
    arr = [series1,series2]
    stacked = np.stack(arr,axis=1)
    print("Vertical Stack:",stacked)
    stacked = np.stack(arr,axis=0)
    print("Horizaontal Stack:",stacked)
    # print out both vertically and horizontally stacked series.
    return None
generate()

Vertical Stack: [[0 'a']
 [1 'b']
 [2 'c']
 [3 'd']
 [4 'e']]
Horizaontal Stack: [[0 1 2 3 4]
 ['a' 'b' 'c' 'd' 'e']]
