<img src = 'https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true' width="240" height="360">
# __Assignment: Numpy and Pandas__
### Level: 2

### 1. Form a 1D array containing elements from -2(including) to 10(excluding) in arithmetic progression with common difference 1.5 , negate all elements which are between 2 and 7, in place. Print out this new array.

In [45]:
import numpy as np
def generate():
    # your code here
    arr_1d = np.arange(-2,10,1.5)
    print(arr_1d)
    s = arr_1d[3:6]
    print(s)
    arr_1d = np.delete(arr_1d,s)
    
    return arr_1d #return modified array
generate()

[-2.  -0.5  1.   2.5  4.   5.5  7.   8.5]
[2.5 4.  5.5]


D:\Sathish\Anaconda\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: using a non-integer array as obj in delete will result in an error in the future
  


array([-2. , -0.5,  2.5,  7. ,  8.5])

### 2. Create random vector of size 7 and replace the maximum value by 2 and minimum by 7. Sort this array in reverse order. Return the modified vector.

In [80]:
import numpy as np
def generate():
    # your code
    ran= np.random.randint(10,size=7)
    print(ran)
    min_ran= np.min(ran)
    print(min_ran)
    max_ran=np.max(ran)
    print(max_ran)
    # print(np.where(np.max(ran), 2, ran))
    # np.place(ran,2,max_ran>0)   
    np.putmask(ran,max_ran>0,2)
    
    return  # your array
generate()

[0 7 6 4 4 5 4]
0
7


ValueError: putmask: mask and data must be the same size

### 3. Convert a random 7x2 matrix representing cartesian coordinates to polar coordinates. Print out both.
Hint: use arctan2().

In [34]:
import numpy as np
def generate():
    # your code here
    # print out both matrices
    return None
generate()

### 4. Create an numpy array sequence named num_seq when only the starting point, step size and length of sequence is given.

In [1]:
import numpy as np

length = 15
start = 5
step = 2

def generate(start, length, step):
    # your code here
    num_seq = np.arange(5,15,2)
    return num_seq # array created by you, i.e. num_seq
generate(start, length, step)

array([ 5,  7,  9, 11, 13])

### 5. Make a 3*3 array using a 1d array of evenly spaced numbers ranging from 0 to 9, name it arr1.<br/> 
### Then transpose it to obtain arr2.  From arr2 subtract a 1*3 array with all elements 1 to get arr4.
HINT: Use reshape and transpose function.

In [22]:
import numpy as np
def generate():
    # your code here
    arr_1d = np.arange(0,9).reshape(3,3)
    print(arr_1d)
    arr2_2d = np.transpose(arr_1d)
    print("Transposed view: ",arr2_2d)
    arr4= arr2_2d - 1
    return arr4 # finally created array i.e arr4
generate()

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Transposed view:  [[0 3 6]
 [1 4 7]
 [2 5 8]]


array([[-1,  2,  5],
       [ 0,  3,  6],
       [ 1,  4,  7]])

### 6. Create a DatetimeIndex that contains each business day of 2016 and use it to index a Series of random numbers. Let's call this Series bus_2k16. Print it out. Hint: use pd.date_range.

In [93]:
import pandas as pd
import numpy as np
def generate():
    # Your code here
    #bus_2k16 = 
    Bd = pd.offsets.BDay()
    index1 = pd.date_range('2016-1-1',periods=300,freq = Bd)
    bus_2k16 = pd.DatetimeIndex(index1) 
    
    print(bus_2k16)
    # print out bus_2k16
    return None
generate()

DatetimeIndex(['2016-01-01', '2016-01-04', '2016-01-05', '2016-01-06',
               '2016-01-07', '2016-01-08', '2016-01-11', '2016-01-12',
               '2016-01-13', '2016-01-14',
               ...
               '2017-02-10', '2017-02-13', '2017-02-14', '2017-02-15',
               '2017-02-16', '2017-02-17', '2017-02-20', '2017-02-21',
               '2017-02-22', '2017-02-23'],
              dtype='datetime64[ns]', length=300, freq='B')


###  7. For each calendar month in dataframe bus_2k16, from previous problem. Print out the mean of values also find the sum of the values in bus_2k16 for every Sunday.

In [8]:
import pandas as pd
def generate():
    # Your code here
    # print out mean
    # print out sum of the values in bus_2k16 for every Sunday.
    return None
generate()

### 8.Given the dataframe df, In the From_To column split each string on the underscore delimiter _ to give a new temporary DataFrame with the correct values. Also standardise the strings so that only the first letter is uppercase (e.g. "londON" should become "London".) Assign the correct column names to this temporary DataFrame named as temp. Return temp.

In [11]:
import numpy as np
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
import pandas as pd
def generate():
    # write your code here
    return # your temporary variable i.e temp.
generate()

### 9. Given a dataFrame with 10 columns of real numbers. Find that column's label which has the smallest sum? Also count the number of unique rows the dataframe has. 
Hint: use idxmin method.

In [12]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.random(size=(4, 10)), columns=list('qrstuvwxyz'))
print(df)
def generate():
    # your code here
    # print out that column's label which has the smallest sum
    # Also count the number of unique rows the dataframe has.
    return None
generate()

          q         r         s         t         u         v         w  \
0  0.365416  0.473422  0.953670  0.556064  0.994396  0.004377  0.381954   
1  0.531423  0.167774  0.198484  0.997754  0.953728  0.214146  0.663055   
2  0.366754  0.486134  0.807647  0.888060  0.192364  0.824071  0.697345   
3  0.248708  0.040752  0.263040  0.228124  0.553965  0.601300  0.410819   

          x         y         z  
0  0.035309  0.355604  0.881858  
1  0.299920  0.145172  0.572647  
2  0.583698  0.458728  0.055934  
3  0.112957  0.285955  0.671356  


### 10. Given a dataFrame df with a column 'int' of integers. Print out the dataframe with filtered out rows which contain the same integer as the row immediately above. Also print out the dataframe after subtracting the mean of all integers from each element .
Hint: use drop_duplicates and sub methods

In [7]:
import pandas as pd
df = pd.DataFrame({'int': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
def generate():
    # your code here
    # Print out the dataframe with filtered out rows which contain the same integer as the row immediately above
    # Print out the dataframe after subtracting the mean of all integers from each element
    return None
generate()